### ISSUE TITLE
BLAST output file contains less than two samples

### ISSUE THREAD

**Issue by ghost** [leylabmpi/SynTracker#8]
Dear all,

I am running **SynTracker v1.3.0** on a haploid fungal reference genome with the default parameters.

For many of the .tab BLAST output files I get an error message, that it contains **less than two samples** and is **skipped**.
Most of the **BATCH numbers fail or finish without any hits**.

The target genomes belong to the same species as the reference genome, and I am wondering if you would advice me to reduce the _region length_, the _BLASTn identity_, or both to get valid hits? Or is any other parameter / problem coming to your mind that could change the SynTracker behavior in this case?

Thanks a lot for your help in advance!

Best regards

**Comment by henav** [comment]
Hi. 
First, I should emphasise that SynTracker was developed to analyse bacterial genomes, so the default paramaters are optimised for this type of analysis - please keep it in mind when doing your downstream analysis, later on. 

As for your problem - what happens is that the BLAST search is not yielding any hits.  It seems that your reference is very different than the target genomes. I would try the following:
1. First, use another reference genome (by the way, how did you choose your reference?). 
2. Lower the blast identity. By default it is set to 97%, I would start with 95% and go down from there. 
3.  If previous steps won't work, reduce the length of the region. 

Good luck, please let us know if any of these steps help. 
Hagay.

**Comment by ghost** [comment]
Dear Hagay,

thanks a lot for your quick response!
I chose the reference genome because it is the only one available, but it is a chromosome level assembly with high completeness.
What is surprising me:
If I check the blast_output folder there are only 208 out of over 35000 .tab files for the different scaffolds that have a size of zero bytes. All the other .tab files have information stored in them. If I understand correctly, if no valid hits are found, the .tab file is empty, but it is really surprising to me, that at this low proportion of empty files, the BLAST search does not finish successfully. Also, the blast search always stops after the same batch-number, even if I reduce the BLAST identity to very low 80%.

Best regards,
Felix

**Comment by henav** [comment]
Hi Felix, 
Could you open one of the smaller non-empty .tab files, and let me know how many hits you see in them? My guess is that they contain only one hit and therefore are filtered out (not enough hits for pairwise comparison in later stages of the pipeline...). 
I'm not sure that the blast search is not finishing unsuccessfully, it seems that it just does not find enough hits. 
The batch is not related to the performance of BLAST. It is related to how we divided the jobs between the cores on your machine. If you did not change the number of cores, it will divide the jobs to the same number of batches in all runs. 

Could you also inform me about the number of target genomes you are using?

Cheers, 
Hagay

**Comment by ghost** [comment]
You are right, the small .tab files only contain one hit. If I include the files with only one hit, there are roughly 5500 out of 35000 files that are filtered out. So around 30000 files should have enough hits for the pairwise comparison when the BLAST search is aborted.
I am only using 4 target genomes (to figure out SynTracker and how to implement it), would you advise me to increase the number of target genomes?

**Comment by inbalpaz** [comment]
Hi Felix,
It would be easier for us to help you, if we can see the dataset that you're running. You can send it to us by email: inbal.paz@tuebingen.mpg.de and we'll have a deeper look into it.
Best,
Inbal
